app1/urls.py
from django.urls import path
from app1.views import *
app_name = 'som'



urlpatterns = [ 
    path('sagar/',sagar,name='sagar'),
]

app2/urls.py
from django.urls import path
from app2.views import *
app_name = 'thing'

urlpatterns = [ 
    path('gangaraj/',gangaraj,name='gangaraj'),
]

project10/urls.py
from django.contrib import admin
from django.urls import path,include
import app1,app2

urlpatterns = [
    path('admin/', admin.site.urls),
    path('app1/',include('app1.urls')),
    path('app2/',include('app2.urls')),
]

app1/models.py
from django.db import models

# Create your models here.

app2/models.py
from django.db import models

# Create your models here.

app1/views.py
from django.shortcuts import render

# Create your views here.
def sagar (request):
    return render(request,'masi.html')

app2/views.py
from django.shortcuts import render

# Create your views here.
def gangaraj (request):
    return render (request,'thati.html')

templates/masi.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1>"MANI ARTS"</h1>
    <h2><a href="{%url 'thing:gangaraj'%}">PLEASE LOG IN </a></h2>

    </center>
    
   
</body>
</html>

templates/thati.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <center>
        <h1> "WELCOME TO MANI ARTS" ,</h1>
           <h1>PRO : K.SUBRAMANYAM</h1> 
           <h1>
            CELL : 9502504906 
           </h1>  
            <h1>
            PLACE : YERRAGUNTLA , KADAPA (DIST), AP. 
            </h1>
        <h2><a href="{% url 'som:sagar' %}"> GO TO HOME PAGE</a></h2>
    </center>
   
</body>
</html>